name: Build release APK

on:
  workflow_dispatch:
  schedule:
  - cron: "0 16 * * *" # Every day at 16:00 UTC

jobs:
  build-release-apk:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-encryption-key: Da25KUVSE5jbGds2zXmfXw==
      - name: Build release APK
        run: ./gradlew assembleLawnWithQuickstepGithubRelease bundleLawnWithQuickstepPlayRelease
      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::$(date +"%Y.%m.%d")"
      - name: Publish to Releases
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.tag.outputs.release_tag }}
          prerelease: true
          files: build/outputs/apk/lawnWithQuickstepGithub/release/*.apk
          tag_name: ${{ steps.tag.outputs.release_tag }}
          