name: Build release APK

on:
  workflow_dispatch:

jobs:
  build-release-apk:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-encryption-key: Da25KUVSE5jbGds2zXmfXw==
      - name: Build release APK
        run: ./gradlew assembleLawnWithQuickstepGithubRelease bundleLawnWithQuickstepPlayRelease
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Release APK
          path: build/outputs/apk/lawnWithQuickstepGithub/release/*.apk
      - name: Publish to Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.date.outputs.date }}
          prerelease: true
          files: build/outputs/apk/lawnWithQuickstepGithub/release/*.apk
          tag_name: test_tag
          