name: Build release APK

permissions:
  actions: write  # Required for the `gh` CLI
  contents: write  # Required for `softprops/action-gh-release`

on:
  workflow_dispatch:
  schedule:
  - cron: "0 14 * * *"  # Every day at 14:00 UTC

jobs:
  build-release-apk:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout LawnchairLauncher/lawnchair
        uses: actions/checkout@v4
        id: checkout
        with:
          repository: LawnchairLauncher/lawnchair
          submodules: true
      - name: Find and Replace versionCode
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "versionCode 14_00_02_03"
          replace: "versionCode 14_00_02_04"
          include: "build.gradle"
      - name: Checkout my repository
        uses: actions/checkout@v4
        with:
          path: my-repo
      - name: Check latest commit
        # Temporarily disabled
        if: false
        run: |
          latest_commit=$(cat my-repo/latest_commit.txt)
          if [ "$latest_commit" = "${{ steps.checkout.outputs.commit }}" ]; then
            echo "${{ steps.checkout.outputs.commit }} is the latest commit. Exiting."
            gh run cancel ${{ github.run_id }}
            gh run watch ${{ github.run_id }}
          else
            echo "Running workflow for commit ${{ steps.checkout.outputs.commit }}."
            echo "Previous commit was $latest_commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
          cache: 'gradle'
      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-encryption-key: Da25KUVSE5jbGds2zXmfXw==
      - name: Build release APK
        run: ./gradlew assembleLawnWithQuickstepGithubRelease
      - name: Generate release tag
        id: tag
        run: echo "release_tag=$(date +"%Y.%m.%d")" >> $GITHUB_OUTPUT
      - name: Publish to Releases
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.tag.outputs.release_tag }}
          prerelease: true
          files: build/outputs/apk/lawnWithQuickstepGithub/release/*.apk
          tag_name: ${{ steps.tag.outputs.release_tag }}
          body: Built using commit ${{ steps.checkout.outputs.commit }}.
      - name: Update latest commit
        # Temporarily disabled
        if: false
        run: |
          cd my-repo
          echo ${{ steps.checkout.outputs.commit }} > latest_commit.txt
          # https://github.com/actions/checkout?tab=readme-ov-file#push-a-commit-using-the-built-in-token
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add latest_commit.txt
          git commit -m "Update latest_commit.txt to ${{ steps.checkout.outputs.commit }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
